---
title: "假设检验"
author: "梁雪枫"
date: "2014年11月18日"
documentclass: ctexart
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
    number_sections: yes
    template: !expr rticles::ctex_template()
    toc: yes
classoption: "hyperref`r if (.Platform$OS.type != 'windows') ',nofonts'`"
---

```{r include=FALSE}
library(TrialSize)
```

假设检验（hypothesis test），就是根据已掌握的资料对一个总体参数是否等于某一个数值，某一随机变量是否服从某种概率分布的假设，然后根据所取得的样本资料，利用一定的统计方法计算出有关检验的统计量，依据一定的概率原则，以较小的风险来判断估计数值与总体数值（或估计分布与实际分布）是否存在显著差异，是否应当接受原假设的一种检验方法 。参数假设检验，是指在总体的分布形式已知的条件下，对总体参数的某一假设进行的检验 。非参数假设检验，是指在总体分布未知时，对其分布的具体形式、特征值等信息进行的假设检验。
假设检验是根据小概率事件的实际不可能性原理来推断的。假设检验中的小概率标准称为显著性水平，用$\alpha$表示。依据显著性水平的大小将检验统计量的所有可能值组成的样本空间分为两个区域 ：否定域或拒绝域：在原假设成立的情况下，如果检验统计量的值落在这个区域里，则否定原假设。接受域：在原假设成立的情况下，如果检验统计量的值没有落在这个区域里，则接受原假设。 假设检验的步骤:1. 建立统计假设,包括原假设,备择假设。2. 确立合适的检验统计量，确定其分布。3. 规定显著性水平 4. 根据样本观测值计算检验，统计量的取值。5. 判断原假设是否成立。假设检验的四种情况

                          $H_{0}$为真         $H_{0}$为假 
---                      --                  -- 
接受$H_{0}$              正确决策              第二类错误 $\beta$
拒绝$H_{0}$              第一类错误$\alpha$    正确决策 

第一类错误，也称弃真错误,本来是真的，却根据检验统计量的值把它给否定了。发生这种错误的概率通常用$\alpha$表示。第二类错误，也称取伪错误，本来是假的，却根据检验统计量的值把它给接受了。

##参数假设检验             
###正态总体均值的假设检验
####单个总体的情况及实例
####两个总体的情况及实例
###正态总体方差的假设检验
###二项分布（非正态）总体的假设检验
##非参数假设检验