---
title: "前言"
author: "梁雪枫"
date: "2014年10月11日"
documentclass: ctexart
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
    number_sections: yes
    template: !expr rticles::ctex_template()
    toc: yes
classoption: "hyperref`r if (.Platform$OS.type != 'windows') ',nofonts'`"
---
R目前仍然不为大众所了解，但并不能妨碍其流行趋势，越来越多的人和行业开始使用R做为数据统计工具。相对于R在其他行业的流行，医学领域R应用更加少见，医学领域目前仍然以SPSS和SAS为主，本书主要目的在于将R应用引入到医学领域。

我在撰写这本书之前，有几个一直困惑我的问题，使得本书的写作迟迟未能开始。问题一：就是如何使得写作更加关注内容，而不是将大部分是时间浪费在排版之上。问题二：如何解决写作过程中从R到Word一遍又一遍复制、粘贴工作。问题三：如何做好良好的版本控制，避免从v1，v2，v3到v20等版本。庆幸的是这三个问题，已经有了完美的解决途径，所以我才能完成此书，不然工作量之大难以想象。本书使用 markdown衍生版本R Markdown（Rmd）V2进行撰写，Markdown是一种非常简洁的标记语言，足以使写作关注于内容而不是形式。knitr包完美的解决了自动报告的问题，使得Markdown和R代码混排，复制和粘贴工作几乎不存在了，代码和结果完美混排。Git用来实现版本控制，GitHub用来进行代码托管，再也不用一个Word又一个Word进行版本控制了。上述问题的解决，使得本书的编排相对容易，不得不感谢前辈们的辛勤付出。

本书定位于对R有简单了解读者，如果读者对基本的语法和相关内容不熟悉，本书不做详细介绍，还请读者参考其他教程。本书假定读者对R、Rmd、Git等相关知识有初步的了解，源代码和书中使用相关数据文件会公布于GitHub（https://github.com/xuefliang/RInMedicine）， 请读者clone在本地进行学习。本书以实际案例分析为主要内容，细致讲解案例所涉及统计学和R语言的相关内容，解决实际工作中存在的问题，也可以本书Rmd为模板，学习如何使数据分析的过程可重复。如何利用R进行实验设计尚不在本书介绍范围。

由于作者水平有限，时间仓促，书中难免有错误和疏漏之处，诚恳地期望各位专家和读者批评指正，对此，将深表感谢。本书源代码托管于GitHub，期望得到共同修缮，联系方式QQ：360149345。